// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dependence.proto

package com.proginn.gitinn.protobuf;

public final class DependenceProto {
  private DependenceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_JavaFrameworkRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_JavaFrameworkRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_JavaFrameworkReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_JavaFrameworkReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dependence.proto\022\004grpc\"+\n\024JavaFramewor" +
      "kRequest\022\023\n\013remote_path\030\001 \001(\t\"(\n\022JavaFra" +
      "meworkReply\022\022\n\ndependence\030\001 \003(\t2`\n\021Depen" +
      "denceService\022K\n\021GetDependenceList\022\032.grpc" +
      ".JavaFrameworkRequest\032\030.grpc.JavaFramewo" +
      "rkReply\"\000B0\n\033com.proginn.gitinn.protobuf" +
      "B\017DependenceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_JavaFrameworkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_JavaFrameworkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_JavaFrameworkRequest_descriptor,
        new java.lang.String[] { "RemotePath", });
    internal_static_grpc_JavaFrameworkReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_JavaFrameworkReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_JavaFrameworkReply_descriptor,
        new java.lang.String[] { "Dependence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
