// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dependence.proto

package com.proginn.gitinn.protobuf;

public interface JavaFrameworkReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.JavaFrameworkReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string dependence = 1;</code>
   */
  com.google.protobuf.ProtocolStringList
      getDependenceList();
  /**
   * <code>repeated string dependence = 1;</code>
   */
  int getDependenceCount();
  /**
   * <code>repeated string dependence = 1;</code>
   */
  java.lang.String getDependence(int index);
  /**
   * <code>repeated string dependence = 1;</code>
   */
  com.google.protobuf.ByteString
      getDependenceBytes(int index);
}
