// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dependence.proto

package com.proginn.gitinn.protobuf;

public interface JavaFrameworkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.JavaFrameworkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string remote_path = 1;</code>
   */
  java.lang.String getRemotePath();
  /**
   * <code>optional string remote_path = 1;</code>
   */
  com.google.protobuf.ByteString
      getRemotePathBytes();
}
